name: Publish

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: docker build . --file Dockerfile --tag douglampe/mkdocs:latest

      - name: Docker Login
        shell: bash
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Publish
        shell: bash
        run: docker push douglampe/mkdocs:latest
